from AEstrela import AEstrela
from No import No
from Aresta import Aresta

print("teste1")
arad = No("Arad", 366)
bucharest = No("Bucharest", 0)
craiova = No("Craiova", 160)
dobreta = No("Dobreta", 242)
eforie = No("Eforie", 161)
fagaras = No("Fagaras", 176)
giurgiu = No("Giurgiu", 77)
hirsova = No("Hirsova", 151)
iasi = No("Iasi", 226)
lugoj = No("Lugoj", 244)
mehadia = No("Mehadia", 241)
neamt = No("Neamt", 234)
oradea = No("Oradea", 380)
pitesti = No("Pitesti", 100)
rimnicu = No("Rimnicu", 193)
sibiu = No("Sibiu", 253)
timisoara = No("Timisoara", 329)
urziceni = No("Urziceni", 80)
vaslui = No("Vaslui", 199)
zerind = No("Zerind", 374)

arad.setAdjacentes([Aresta(zerind, 75), Aresta(sibiu, 140), Aresta(timisoara, 118)])
zerind.setAdjacentes([Aresta(arad, 75), Aresta(oradea, 71)])
oradea.setAdjacentes([Aresta(zerind, 71), Aresta(sibiu, 151)])
sibiu.setAdjacentes([Aresta(arad, 140), Aresta(fagaras, 99), Aresta(oradea, 151), Aresta(rimnicu, 80)])
fagaras.setAdjacentes([Aresta(sibiu, 99), Aresta(bucharest, 211)])
rimnicu.setAdjacentes([Aresta(sibiu, 80), Aresta(pitesti, 97), Aresta(craiova, 146)])
pitesti.setAdjacentes([Aresta(rimnicu, 97), Aresta(bucharest, 101), Aresta(craiova, 138)])
timisoara.setAdjacentes([Aresta(arad, 118), Aresta(lugoj, 111)])
lugoj.setAdjacentes([Aresta(timisoara, 111), Aresta(mehadia, 70)])
mehadia.setAdjacentes([Aresta(lugoj, 70), Aresta(dobreta, 75)])
dobreta.setAdjacentes([Aresta(mehadia, 75), Aresta(craiova, 120)])
craiova.setAdjacentes([Aresta(dobreta, 120), Aresta(rimnicu, 146), Aresta(pitesti, 138)])
bucharest.setAdjacentes([Aresta(pitesti, 101), Aresta(giurgiu, 90), Aresta(fagaras, 211)])
giurgiu.setAdjacentes([Aresta(bucharest, 90)])

aestrela = AEstrela()
aestrela.buscaAEstrela(arad, bucharest)
print(aestrela.percorrerCaminho(bucharest))